query ordersAvailableToReturn(
  $page: Int!
  $storeUserEmail: String
  $isAdmin: Boolean
  $filters: OrdersFilters
) {
  ordersAvailableToReturn(
    page: $page
    storeUserEmail: $storeUserEmail
    isAdmin: $isAdmin
    filters: $filters
  ) @context(provider: "vtex.return-app") {
    list {
      orderId
      sellerName
      creationDate
      invoicedItems {
        id
        productId
        quantity
      }
      processedItems {
        itemIndex
        quantity
      }
      excludedItems {
        itemIndex
      }
    }
    paging {
      total
      pages
      currentPage
      perPage
    }
  }
}
