fragment ReturnDetailsAdminFragment on ReturnRequestResponse {
  id
  status
  items {
    orderItemIndex
    name
    sellingPrice
    tax
    quantity
  }
  refundableAmountTotals {
    id
    value
  }
}
