fragment ReturnDetailsAdminFragment on ReturnRequestResponse {
  id
  status
  items {
    orderItemIndex
    name
    sellingPrice
    tax
    quantity
  }
  refundableAmountTotals {
    id
    value
  }
  customerProfileData {
    name
    email
    phoneNumber
  }
  pickupReturnData {
    country
    city
    address
    state
    zipCode
  }
}
