fragment ReturnDetailsAdminFragment on ReturnRequestResponse {
  id
  status
  refundableAmount
  items {
    orderItemIndex
    name
    sellingPrice
    tax
    quantity
    imageUrl
    sellerName
    refId
    returnReason {
      reason
      otherReason
    }
  }
  refundableAmountTotals {
    id
    value
  }
  refundData {
    refundedShippingValue
    invoiceValue
    items {
      orderItemIndex
      quantity
      price
      restockFee
    }
  }
  customerProfileData {
    name
    email
    phoneNumber
  }
  pickupReturnData {
    country
    city
    address
    state
    zipCode
    addressType
  }
  refundStatusData {
    status
    submittedBy
    createdAt
    comments {
      comment
      createdAt
      visibleForCustomer
      submittedBy
    }
  }
}
