mutation CreateReturn(
  $returnRequest: ReturnRequestInput!
  $returnedItems: [ProductReturnedInput!]!
) {
  createReturnRequest(
    returnRequest: $returnRequest
    returnedItems: $returnedItems
    authToken: STORE_TOKEN
  ) {
    returnRequestId
  }
}
