query storeAppSettings {
  returnAppSettings @context(provider: "itglobers.return-app") {
    orderStatus
    termsUrl
    customReturnReasons {
      reason
      maxDays
      translations {
        locale
        translation
      }
    }
    paymentOptions {
      enablePaymentMethodSelection
      allowedPaymentTypes {
        bank
        card
        giftCard
      }
    }
    options {
      enableOtherOptionSelection
      enablePickupPoints
      enableSelectItemCondition
      enableHighlightFormMessage
    }
  }
}
